//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModels.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Auth {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Auth() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewModels.Lang.Auth", typeof(Auth).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Settings.
        /// </summary>
        public static string Auth_AccountSettings {
            get {
                return ResourceManager.GetString("Auth_AccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Failed.
        /// </summary>
        public static string Auth_AuthorizationFailed {
            get {
                return ResourceManager.GetString("Auth_AuthorizationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Required.
        /// </summary>
        public static string Auth_AuthorizationRequired {
            get {
                return ResourceManager.GetString("Auth_AuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization Successful.
        /// </summary>
        public static string Auth_AuthorizationSuccess {
            get {
                return ResourceManager.GetString("Auth_AuthorizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        public static string Auth_Connect {
            get {
                return ResourceManager.GetString("Auth_Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected.
        /// </summary>
        public static string Auth_Connected {
            get {
                return ResourceManager.GetString("Auth_Connected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected as {0}.
        /// </summary>
        public static string Auth_ConnectedAs {
            get {
                return ResourceManager.GetString("Auth_ConnectedAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting....
        /// </summary>
        public static string Auth_Connecting {
            get {
                return ResourceManager.GetString("Auth_Connecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Account.
        /// </summary>
        public static string Auth_CreateAccount {
            get {
                return ResourceManager.GetString("Auth_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        public static string Auth_Disconnect {
            get {
                return ResourceManager.GetString("Auth_Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected.
        /// </summary>
        public static string Auth_Disconnected {
            get {
                return ResourceManager.GetString("Auth_Disconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Auth_Email {
            get {
                return ResourceManager.GetString("Auth_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string Auth_ForgotPassword {
            get {
                return ResourceManager.GetString("Auth_ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Token.
        /// </summary>
        public static string Auth_GenerateToken {
            get {
                return ResourceManager.GetString("Auth_GenerateToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid credentials.
        /// </summary>
        public static string Auth_InvalidCredentials {
            get {
                return ResourceManager.GetString("Auth_InvalidCredentials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Link Account.
        /// </summary>
        public static string Auth_LinkAccount {
            get {
                return ResourceManager.GetString("Auth_LinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign In.
        /// </summary>
        public static string Auth_Login {
            get {
                return ResourceManager.GetString("Auth_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Out.
        /// </summary>
        public static string Auth_Logout {
            get {
                return ResourceManager.GetString("Auth_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access token is missing.
        /// </summary>
        public static string Auth_MissingToken {
            get {
                return ResourceManager.GetString("Auth_MissingToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Browser.
        /// </summary>
        public static string Auth_OpenInBrowser {
            get {
                return ResourceManager.GetString("Auth_OpenInBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Auth_Password {
            get {
                return ResourceManager.GetString("Auth_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password missmatch.
        /// </summary>
        public static string Auth_PasswordMissmatch {
            get {
                return ResourceManager.GetString("Auth_PasswordMissmatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat Password.
        /// </summary>
        public static string Auth_PasswordRepeat {
            get {
                return ResourceManager.GetString("Auth_PasswordRepeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Auth_Profile {
            get {
                return ResourceManager.GetString("Auth_Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Azure DevOps.
        /// </summary>
        public static string Auth_Provider_AzureDevOps {
            get {
                return ResourceManager.GetString("Auth_Provider_AzureDevOps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with Bitbucket.
        /// </summary>
        public static string Auth_Provider_Bitbucket {
            get {
                return ResourceManager.GetString("Auth_Provider_Bitbucket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with GitHub.
        /// </summary>
        public static string Auth_Provider_GitHub {
            get {
                return ResourceManager.GetString("Auth_Provider_GitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with GitLab.
        /// </summary>
        public static string Auth_Provider_GitLab {
            get {
                return ResourceManager.GetString("Auth_Provider_GitLab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Auth_RememberMe {
            get {
                return ResourceManager.GetString("Auth_RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repositories.
        /// </summary>
        public static string Auth_Repositories {
            get {
                return ResourceManager.GetString("Auth_Repositories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string Auth_ResetPassword {
            get {
                return ResourceManager.GetString("Auth_ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Provider.
        /// </summary>
        public static string Auth_SelectProvider {
            get {
                return ResourceManager.GetString("Auth_SelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server URL.
        /// </summary>
        public static string Auth_ServerUrl {
            get {
                return ResourceManager.GetString("Auth_ServerUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        public static string Auth_SigningIn {
            get {
                return ResourceManager.GetString("Auth_SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing out....
        /// </summary>
        public static string Auth_SigningOut {
            get {
                return ResourceManager.GetString("Auth_SigningOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        public static string Auth_SignUp {
            get {
                return ResourceManager.GetString("Auth_SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access Token.
        /// </summary>
        public static string Auth_Token {
            get {
                return ResourceManager.GetString("Auth_Token", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste your personal access token here.
        /// </summary>
        public static string Auth_TokenHint {
            get {
                return ResourceManager.GetString("Auth_TokenHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlink Account.
        /// </summary>
        public static string Auth_UnlinkAccount {
            get {
                return ResourceManager.GetString("Auth_UnlinkAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username.
        /// </summary>
        public static string Auth_Username {
            get {
                return ResourceManager.GetString("Auth_Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string df {
            get {
                return ResourceManager.GetString("df", resourceCulture);
            }
        }
    }
}
