//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ViewModels.Lang {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Git {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Git() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ViewModels.Lang.Git", typeof(Git).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checkout.
        /// </summary>
        public static string Action_Checkout {
            get {
                return ResourceManager.GetString("Action_Checkout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clone Repository.
        /// </summary>
        public static string Action_Clone {
            get {
                return ResourceManager.GetString("Action_Clone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commit Changes.
        /// </summary>
        public static string Action_Commit {
            get {
                return ResourceManager.GetString("Action_Commit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Branch.
        /// </summary>
        public static string Action_CreateBranch {
            get {
                return ResourceManager.GetString("Action_CreateBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Branch.
        /// </summary>
        public static string Action_DeleteBranch {
            get {
                return ResourceManager.GetString("Action_DeleteBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialize Repository.
        /// </summary>
        public static string Action_Init {
            get {
                return ResourceManager.GetString("Action_Init", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge Branch.
        /// </summary>
        public static string Action_Merge {
            get {
                return ResourceManager.GetString("Action_Merge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pull from Remote.
        /// </summary>
        public static string Action_Pull {
            get {
                return ResourceManager.GetString("Action_Pull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Push to Remote.
        /// </summary>
        public static string Action_Push {
            get {
                return ResourceManager.GetString("Action_Push", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebase.
        /// </summary>
        public static string Action_Rebase {
            get {
                return ResourceManager.GetString("Action_Rebase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stash Changes.
        /// </summary>
        public static string Action_Stash {
            get {
                return ResourceManager.GetString("Action_Stash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge conflict detected.
        /// </summary>
        public static string Error_MergeConflict {
            get {
                return ResourceManager.GetString("Error_MergeConflict", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Git repository found.
        /// </summary>
        public static string Error_NoRepository {
            get {
                return ResourceManager.GetString("Error_NoRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Branch.
        /// </summary>
        public static string Label_Branch {
            get {
                return ResourceManager.GetString("Label_Branch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changes.
        /// </summary>
        public static string Label_Changes {
            get {
                return ResourceManager.GetString("Label_Changes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commits.
        /// </summary>
        public static string Label_Commits {
            get {
                return ResourceManager.GetString("Label_Commits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staged Changes.
        /// </summary>
        public static string Label_Staged {
            get {
                return ResourceManager.GetString("Label_Staged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unstaged Changes.
        /// </summary>
        public static string Label_Unstaged {
            get {
                return ResourceManager.GetString("Label_Unstaged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repo Initialized.
        /// </summary>
        public static string Result_RepoInitialized {
            get {
                return ResourceManager.GetString("Result_RepoInitialized", resourceCulture);
            }
        }
    }
}
